version: '3'
services:
  web:
    build: .
    ports:
      - "5000:80"
    container_name: my-web-container
  database:
    image: mongo
    ports:
      - "27017:27017"
    container_name: my-database-container